### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 409geekhzy** [HamedHojatian/CF-mMIMO-HBF#2]
Good work, sir.
I don't understand this sentence(The RSSI value must be normalized and the order of data in .npy can be found in codes (import .npy).)
How can I normalized RSSI value.?

'RuntimeError: shape '[4, 4, 4, 32]' is invalid for input of size 0'
This is an error reported during code runtime. Could you please help me? Thank you！

**Comment by HamedHojatian** [comment]
In case the RSSIs are not normalized, they should be in [0,1]. About the error, I need more information about the line the error came from. In any case, it is related to the shape of the data you are calling.

**Comment by 409geekhzy** [comment]
Thank you for your reply,sir.
 In fact, I don't understand where RSSI data comes from, which is the problem (I am planning to study your paper again). Whenever I run Main_ CF files, always in Inputs_ Reg = Networks_ Main_ Menu.Inp_ MT (RSSI) stopped running here, so I tried to output the shape of RSSI and received the following feedback:
Traceback (most recent call last):

File "C:/Users/DELL/Desktop/MIMO/CF-mMIMO-HBF-main/CF-mMIMO-HBF-main/Main_CF.py", line 155, in <module>

Inputs_ Reg = Networks_ Main_ Menu.Inp_ MT(RSSI)

File "C:\Users\DELL\Desktop\MIMO\CF-mMIMO-HBF-main\CF-mMIMO-HBF-main\networks_activation_CF.py", line 60, in Inp_ MT

Inputs_ MT = RSSI.reshape(len(RSSI), self.Us, self.N_ BS, self.K)[:, :, :, 0:self.K_limited].permute(0, 2, 1, 3).float().to(self.device)

RuntimeError: shape '[4, 4, 4, 32]' is invalid for input of size 0

torch.Size([4, 0])

I went to read your recommendation paper about DeepMIMO written in readme, but I don't understand if this RSSI comes from here, or why running the code would cause the shape of the RSSI to not match. My professional abilities are not strong enough. Thank you again.

**Comment by HamedHojatian** [comment]
You have to compute the RSSI based on the CSI generated from the deepMIMO and the SSB explained in the paper. In the first stage you can consider random SSB to generate the RSSIs. The line you are receiving error is simply reshape the input of the DNN to (sample size, number of APs, number of users, number of K). When using data loader try to make it a 4 dimension tensor.
Good Luck!

**Comment by 409geekhzy** [comment]
Sir, I found that the main reason why I couldn't run successfully was due to an issue with the generation of my npy data file:

import numpy as np

# data = np.zeros((5, 64))
data=np.random.randn()# M*(channel,RSSI),c_shape=(4,64,8,4)
# 将 ndarray 类型的数据以字典的形式保存在扩展名为 npz 的数据文件中
# data[0][0] = 4
# data[1][0] = 4
# data[2][0] = 8
# data[3][0] = 32
# data[4][0] = 4
np.save("dataSet4x64x8x4/dataSet4x64x8x4/130dB/dataSet_130.npy", data)
I tried this for a few days but it didn't work. If it's convenient, could you please provide me with the data file you ran at the time, or could you provide me with a project that can run? Because my supervisor asked me to understand and run your project, and I haven't been successful for a week. It hasn't been long since ddl.

**Comment by 409geekhzy** [comment]
Sir, I found that the main reason why I couldn't run successfully was due to an issue with the generation of my npy data file:
![图片](https://user-images.githubusercontent.com/131285507/235596915-45864c6e-894d-4093-8bfe-359040731039.png)

I tried this for a few days but it didn't work. If it's convenient, could you please provide me with the data file you ran at the time, or could you provide me with a project that can run? Because my supervisor asked me to understand and run your project, and I haven't been successful for a week. It hasn't been long since ddl.

**Comment by HamedHojatian** [comment]
It is very simple to create the .npy file. First generate the CSI from deepMIMO for any number of samples you want to train. Then based on the generated CSI and SSB (the SSB file is available) you can compute the RSSI for each user and access point, then you would be able to feed these RSSI to the DNN. Next, the output of the DNN would be the hybrid beamforming vectors. Since you would need the CSI to compute the loss function, the .npy contains CSI + RSSI.
I will generate the dataset. However, I am not expecting soon.

**Comment by 409geekhzy** [comment]
Thank you very much. It is an honor for me to receive your guidance. Sharing source code for such a high-level paper is extremely rare since I read many papers in this field, so I am constantly trying to understand and learn it. Once again, I would like to express my gratitude to you. My email is geekhzy@163.com

**Comment by 409geekhzy** [comment]
sir

**Comment by 409geekhzy** [comment]
Excuse me ,sir.
I would like to know if the npy file has been generated. If it's convenient, could you please give it to me? My supervisor may need to talk to me in the next few days to understand my progress. If I can't continue with this, I may need to replace it and lose all my previous efforts.
